plugin: netbox.netbox.nb_inventory
api_endpoint: http://k8s-netbox-netboxin-c0519ddf3b-602899348.us-east-1.elb.amazonaws.com
token: CF7gueK8fqOW0Km7fgCAKOA1bLKVFyMYo1rTmEny
validate_certs: false

group_by:
  - device_roles

query_filters:
<<<<<<< HEAD
  - role: k8s-node
=======
  - role: Kubernetes Node
>>>>>>> a1ae37e (Sync Kubernetes manifests, NetBox, Grafana, and inventory updates)
